import type { Metadata } from "next";
import "./globals.css";
import { openSans, dancingScript } from "@/utils/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${dancingScript.variable} overflow-x-hidden`}>{children}</body>
    </html>
  );
}
